name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the name of your default branch, like 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # or './public' or './dist' if your index.html is in a subdirectory